query AllNews($first: Int, $offset: Int) {
  newsArticles(first: $first, offset: $offset) {
    totalResults
    newsList{
      id
      url
      title
      company {
        uid
        name
      }
      category
      publishDate
      creationTime
    }
  }
}
