query NewsSearch($first: Int, $offset: Int, $title: String) {
  newsArticles(first: $first, offset: $offset, searchTitle: $title) {
    totalResults
    newsList{
      id
      url
      title
      company {
        uid
        name
      }
      category
      publishDate
      creationTime
    }
  }
}
