query AllJobs(
  $first: Int,
  $offset: Int
) {
  salesavantJobs(first: $first, offset: $offset) {
    totalResults
    salesavantJobsList {
      uid
      creationTime
      modificationTime
      jobType
      description
      result
      status
      additionalData
    }
  }
}
