query SinglePlaylist($uid: String) {
  playlist(uid: $uid) {
    uid
    name
    creationTime
    accountId
    userId
    companies {
      uid
      name
      signalsCount
      status
      description
      city
      state
      country
      numEmployees
      momentum
      url
    }
  }
}
