query SinglePlaylist($uid: String) {
  playlistCompanies(playlistUid: $uid){
    companiesList{
      uid
      name
      description
      city
      state
      country
      momentum
      numEmployees
      website
      url
      vertical
      totalScore
      totalSignals
    }
  }
}
