query SinglePlaylist($uid: String $first: Int $offset: Int) {
  playlistCompanies(playlistUid: $uid first: $first offset: $offset){
    totalResults,
    companiesList{
      uid
      name
      description
      city
      state
      country
      momentum
      numEmployees
      website
      url
      vertical
      totalScore
      totalSignals
    }
  }
}
