query AllPlaylists(
  $search: String,
  $first: Int,
  $offset: Int,
  $sortBy: String,
  $sortOrder: String
) {
  playlists(search:$search, first: $first, offset: $offset, sortBy: $sortBy, sortOrder: $sortOrder ) {
    totalResults
    playlistsList{
      uid
      name
      creationTime
      accountId
      userId
      totalSignals
      totalCompanies
    }
  }
}
