query AllContacts($uid: String) {
  contact(uid: $uid) {
    creationTime
    modificationTime
    uid
    fullName
    personalEmail
    personalPhone
    bio
    linkedinHandle
    additionalData
    companies {
      title
      businessEmail
      businessPhone
      bioUrl
      bio
      isCurrent
    }
  }
}
