query AllContacts(
  $search: String,
  $first: Int, 
  $offset: Int,
) {
   contacts(search: $search, first: $first, offset: $offset ) {
    totalResults
    contactsList {
      fullName
      personalEmail
      personalPhone
      bio
      linkedinHandle
      additionalData
    }
  }
}
