query AllCompanies(
  $first: Int, 
  $offset: Int,
  $sortBy: String,
  $sortOrder: String
) {
  companies(first: $first, offset: $offset, sortBy: $sortBy, sortOrder: $sortOrder ) {
    totalResults
    companiesList {
      uid
      name
      status
      description
      city
      state
      country
      numEmployees
      momentum
      url
      vertical
      totalScore
      totalSignals
    }
  }
}
