query SelecteCompany($company: String, $playlist: String){
  company(uid: $company){
    creationTime
    modificationTime
    uid
    name
    description
    url
    handle
    logoUrl
    city
    country
    region
    state
    numEmployees
    momentum
    vertical
    industry
    status
    dateFounded
    dateAcquired
    linkedinHandle
    stockSymbol
    naicsCode
    employees{
      title
    }
    signals{
      score
    }
  	news{
      company{
        name
      }
			title
      url
      publishDate
      category
    }
    playlists{
      name 
    } 
  }
  playlist(uid: $playlist) {
    name
  }
}