query SelecteCompany($companyUid: String){
  company(uid: $companyUid){
    creationTime
    modificationTime
    uid
    name
    description
    url
    handle
    logoUrl
    city
    country
    region
    state
    numEmployees
    momentum
    vertical
    industry
    status
    dateFounded
    dateAcquired
    linkedinHandle
    stockSymbol
    naicsCode
    totalScore
    totalSignals
  }
}