query CompaniesAdvancedSearch(
  $name: String
  $website: String
  $description: String
  $country: String
  $city: String
  $region: String
  $state: String
  $status: String
  $lessThanEmployees: Int
  $moreThanEmployees: Int
  $moreThanScore: Float
  $lessThanScore: Float
  $first: Int
  $playlistUid: String,
  $offset: Int
) {
  companies(
    searchName: $name
    searchWebsite: $website
    searchDescription: $description
    country: $country
    city: $city
    region: $region
    state: $state
    status: $status
    lessThanEmployees: $lessThanEmployees
    moreThanEmployees: $moreThanEmployees
    moreThanScore: $moreThanScore
    lessThanScore: $lessThanScore
    first: $first
    playlistUid: $playlistUid
    offset: $offset
  ) {
    creationTime
    modificationTime
    uid
    name
    website
    description
    url
    handle
    logoUrl
    city
    country
    region
    state
    numEmployees
    momentum
    vertical
    industry
    status
    dateFounded
    dateAcquired
    linkedinHandle
    stockSymbol
    naicsCode
    totalScore
    totalSignals
  }
}
