query CompaniesAdvancedSearch(
  $playlistUid: String,
  $signals: [Int],
  $signalGroups: [String],
  $name: String
  $website: String
  $description: String
  $country: String
  $city: String
  $region: String
  $state: String
  $status: String
  $lessThanEmployees: Int
  $moreThanEmployees: Int
  $moreThanScore: Float
  $lessThanScore: Float
  $sortBy: String,
  $sortOrder: String
  $first: Int
  $offset: Int,
  $totalResults: Int
) {
  companies(
    playlistUid: $playlistUid
    signals: $signals
    signalGroups: $signalGroups
    searchName: $name
    searchWebsite: $website
    searchDescription: $description
    country: $country
    city: $city
    region: $region
    state: $state
    status: $status
    lessThanEmployees: $lessThanEmployees
    moreThanEmployees: $moreThanEmployees
    moreThanScore: $moreThanScore
    lessThanScore: $lessThanScore
    sortBy: $sortBy
    sortOrder: $sortOrder
    first: $first
    offset: $offset
    totalResults: $totalResults
  ) {
    totalResults
    companiesList {
      creationTime
      modificationTime
      uid
      name
      website
      description
      url
      handle
      logoUrl
      city
      country
      region
      state
      numEmployees
      momentum
      vertical
      industry
      status
      dateFounded
      dateAcquired
      linkedinHandle
      stockSymbol
      naicsCode
      totalScore
      totalSignals
    }
    
  }
}
