query companySignalsAggs ($first: Int, $offset: Int) {
    companySignalsAggs (first: $first, offset: $offset) {
        signal {
            id
            name
            description
            defaultScore
            group
        }
        totalCompanies
    }
}