query SearchsSignals(
  $search: String, 
  $group: String, 
  $category: String, 
  $first: Int, 
  $offset: Int) {
  signals(
    search: $search,
    group: $group, 
    category: $category,
    first: $first
    offset: $offset) {
    id
    name
  	user {
  	  id
  	}
    group
    userId
    account {
      id
    }
    category
    accountId
    description
    creationTime
    defaultScore
    modificationTime
  }
}