query AllSignals($first: Int, $offset: Int) {
  signals(first: $first offset: $offset) {
    totalResults
    signalsList{
          id
    name
    user {
      id
    }
    group
    userId
    account {
      id
    }
    category
    accountId
    description
    creationTime
    defaultScore
    modificationTime
    }
  }
}
