query AllSignals($first: Int, $offset: Int) {
  signals(first: $first offset: $offset) {
    totalResults
    signalsList{
      id
      userId
      user {
        id
      }
      account {
        id
      }
      name
      group
      category
      accountId
      description
      creationTime
      defaultScore
      modificationTime
    }
  }
}
